header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: 'world'
id: 'environment'
type: {key: '', db: ''}
primitives:
  - type: 1
    dimensions: [0.1, 0.1, 0.1]
primitive_poses:
  - position: {x: 0.0, y: 0.0, z: 0.0}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 0.0}
meshes: 
  - triangles:
      - vertex_indices: [0, 0, 0]
    vertices:
    - {x: 0.0, y: 0.0, z: 0.0}
mesh_poses:
- position: {x: 0.0, y: 0.0, z: 0.0}
  orientation: {x: 0.0, y: 0.0, z: 0.0, w: 0.0}
planes:
- coef: [0.0, 0.0, 0.0, 0.0]
plane_poses:
- position: {x: 0.0, y: 0.0, z: 0.0}
  orientation: {x: 0.0, y: 0.0, z: 0.0, w: 0.0}
operation: 0