controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint
  - name: fake_right_hand_arm_controller
    joints:
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint
      - right_hand_synergy_joint
  - name: fake_head_controller
    joints:
      - head_neck_pitch_joint
      - head_neck_roll_joint
      - head_neck_yaw_joint
      - head_head_tilt_joint
      - head_eyes_tilt_joint
      - head_left_eye_joint
      - head_right_eye_joint
  - name: fake_left_arm_controller
    joints:
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
  - name: fake_left_hand_arm_controller
    joints:
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
      - left_hand_synergy_joint
  - name: fake_full_robot_controller
    joints:
      - head_neck_pitch_joint
      - head_neck_roll_joint
      - head_neck_yaw_joint
      - head_head_tilt_joint
      - head_eyes_tilt_joint
      - head_left_eye_joint
      - head_right_eye_joint
      - left_arm_0_joint
      - left_arm_1_joint
      - left_arm_2_joint
      - left_arm_3_joint
      - left_arm_4_joint
      - left_arm_5_joint
      - left_arm_6_joint
      - left_hand_synergy_joint
      - right_arm_0_joint
      - right_arm_1_joint
      - right_arm_2_joint
      - right_arm_3_joint
      - right_arm_4_joint
      - right_arm_5_joint
      - right_arm_6_joint
      - right_hand_synergy_joint