controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_arm_a1_joint
      - right_arm_a2_joint
      - right_arm_e1_joint
      - right_arm_a3_joint
      - right_arm_a4_joint
      - right_arm_a5_joint
      - right_arm_a6_joint
  - name: fake_right_hand_arm_controller
    joints:
      - right_arm_a1_joint
      - right_arm_a2_joint
      - right_arm_e1_joint
      - right_arm_a3_joint
      - right_arm_a4_joint
      - right_arm_a5_joint
      - right_arm_a6_joint
  - name: fake_head_controller
    joints:
      - head_neck_pitch_joint
      - head_neck_roll_joint
      - head_neck_yaw_joint
      - head_head_tilt_joint
      - head_eyes_tilt_joint
      - head_left_eye_joint
      - head_right_eye_joint
  - name: fake_left_arm_controller
    joints:
      - left_arm_a1_joint
      - left_arm_a2_joint
      - left_arm_e1_joint
      - left_arm_a3_joint
      - left_arm_a4_joint
      - left_arm_a5_joint
      - left_arm_a6_joint
  - name: fake_left_hand_arm_controller
    joints:
      - left_arm_a1_joint
      - left_arm_a2_joint
      - left_arm_e1_joint
      - left_arm_a3_joint
      - left_arm_a4_joint
      - left_arm_a5_joint
      - left_arm_a6_joint
  - name: fake_full_robot_controller
    joints:
      - head_neck_pitch_joint
      - head_neck_roll_joint
      - head_neck_yaw_joint
      - head_head_tilt_joint
      - head_eyes_tilt_joint
      - head_left_eye_joint
      - head_right_eye_joint
      - left_arm_a1_joint
      - left_arm_a2_joint
      - left_arm_e1_joint
      - left_arm_a3_joint
      - left_arm_a4_joint
      - left_arm_a5_joint
      - left_arm_a6_joint
      - right_arm_a1_joint
      - right_arm_a2_joint
      - right_arm_e1_joint
      - right_arm_a3_joint
      - right_arm_a4_joint
      - right_arm_a5_joint
      - right_arm_a6_joint
  - name: fake_dual_hand_arm_controller
    joints:
      - left_arm_a1_joint
      - left_arm_a2_joint
      - left_arm_e1_joint
      - left_arm_a3_joint
      - left_arm_a4_joint
      - left_arm_a5_joint
      - left_arm_a6_joint
      - right_arm_a1_joint
      - right_arm_a2_joint
      - right_arm_e1_joint
      - right_arm_a3_joint
      - right_arm_a4_joint
      - right_arm_a5_joint
      - right_arm_a6_joint