# make the namespace match the name you use to instantiate the arm in the xacro
left_arm:
  root: left_arm_base_link
  tip: left_arm_7_link

# make the namespace match the name you use to instantiate the arm in the xacro
right_arm:
  root: vito_anchor
  tip: probe_tip_touch