left_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - left_arm_a1_joint
      - left_arm_a2_joint
      - left_arm_e1_joint
      - left_arm_a3_joint
      - left_arm_a4_joint
      - left_arm_a5_joint
      - left_arm_a6_joint
  joint_impedance_controller:
    type: lwr_controllers/JointImpedanceController
    root_name: left_arm_base_link
    tip_name: left_arm_7_link
    stiffness_gains: 1000
    damping_gains: 0.5

right_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - right_arm_a1_joint
      - right_arm_a2_joint
      - right_arm_e1_joint
      - right_arm_a3_joint
      - right_arm_a4_joint
      - right_arm_a5_joint
      - right_arm_a6_joint